### ISSUE TITLE
Errors when attempting to upgrade to discord.js v14.4.0

### ISSUE THREAD

**Issue by dreeves** [dreeves/lexiguess#59]
I see this in the console:

```
/rbd/pnpm-volume/04bb14a2-4ffb-4cf5-b41c-3189fc881211/node_modules/discord.js/src/util/BitField.js:168
    throw new RangeError(ErrorCodes.BitFieldInvalid, bit);
    ^
RangeError [BitFieldInvalid]: Invalid bitfield flag or number: GUILDS.
    at Function.resolve (/rbd/pnpm-volume/04bb14a2-4ffb-4cf5-b41c-3189fc881211/node_modules/discord.js/src/util/BitField.js:168:11)
    at /rbd/pnpm-volume/04bb14a2-4ffb-4cf5-b41c-3189fc881211/node_modules/discord.js/src/util/BitField.js:163:54
    at Array.map (<anonymous>)
    at Function.resolve (/rbd/pnpm-volume/04bb14a2-4ffb-4cf5-b41c-3189fc881211/node_modules/discord.js/src/util/BitField.js:163:40)
    at Client._validateOptions (/rbd/pnpm-volume/04bb14a2-4ffb-4cf5-b41c-3189fc881211/node_modules/discord.js/src/client/Client.js:482:41)
    at new Client (/rbd/pnpm-volume/04bb14a2-4ffb-4cf5-b41c-3189fc881211/node_modules/discord.js/src/client/Client.js:78:10)
at Object.<anonymous> (/app/app.js:35:17)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'BitFieldInvalid'
}
```

Version 13.11.0 is the latest one that works.

**Comment by jakecoble** [comment]
Haven't been able to reproduce this. Can you confirm that it's still an issue?
